export class Placa{
    "FSlaca":string;
    "marca":any;
    "modelo":any;
    "anio":any;
    "color":any;
    "clase":any;
    "servicio":any;
    "aniom":any;
    "fecham":any;
    "fechac":any;
    "combustibles":any;
    "marcas":any;
    "combustible":any;
    "traccion":any;
    "transmision":any;
    "tracciones":any;
    "transmisiones":any;
}